provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  insert-priceevent:
    lang: node10-express
    handler: ./insert-priceevent
    image:  nathancriel/insert-priceevent
    labels:
      com.openfaas.scale.min: 6
      com.openfaas.scale.max: 50
      com.openfaas.scale.factor: 20
    environment:
      write_timeout: 10s
      read_timeout: 10s
      mongo: "mongodb.default.svc.cluster.local"
      password: "deltaproject01"
   